name: Testing the copy of repo
on: [push,workflow_dispatch]
jobs:
 testing:
  runs-on: ubuntu-latest
  steps:
  - name: copying the code
    uses: actions/checkout@v4
  - name: checking the files 
    run: ls -la
    
  
