name: Testing the copy of repo
on: workflow_dispatch
jobs:
 testing:
  runs-on: ubuntu-latest
  steps:
  - name: copying the code
    uses: actions/checkout@v4
  - name: checking the files 
    run: echo ls -ls
    
  
